### ISSUE TITLE
Add Github Actions Badge

### ISSUE THREAD

**Issue by spresnac-trox** [spresnac/laravel-url-helper#8]
Image: `https://github.com/spresnac/laravel-url-helper/workflows/Auto%20testings/badge.svg`

Markdown: `[![CI Status](https://github.com/spresnac/laravel-url-helper/workflows/Auto%20testings/badge.svg)](https://github.com/spresnac/laravel-url-helper/actions)`

**Comment by spresnac** [comment]
fixed with https://github.com/spresnac/laravel-url-helper/commit/41d3577578fb30865a3b53d95de1722fc562fcf6
-close-
